//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 10:45:44 PM IST 
//


package com.csw.data.nvd.jaxb.vendorstatement;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.csw.data.nvd.jaxb.vendorstatement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Vendorstatements_QNAME = new QName("http://nvd.nist.gov/feeds/nvdcvestatements", "vendorstatements");
    private final static QName _Statement_QNAME = new QName("http://nvd.nist.gov/feeds/nvdcvestatements", "statement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.csw.data.nvd.jaxb.vendorstatement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VendorstatementsType }
     * 
     */
    public VendorstatementsType createVendorstatementsType() {
        return new VendorstatementsType();
    }

    /**
     * Create an instance of {@link StatementType }
     * 
     */
    public StatementType createStatementType() {
        return new StatementType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VendorstatementsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nvd.nist.gov/feeds/nvdcvestatements", name = "vendorstatements")
    public JAXBElement<VendorstatementsType> createVendorstatements(VendorstatementsType value) {
        return new JAXBElement<VendorstatementsType>(_Vendorstatements_QNAME, VendorstatementsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nvd.nist.gov/feeds/nvdcvestatements", name = "statement")
    public JAXBElement<StatementType> createStatement(StatementType value) {
        return new JAXBElement<StatementType>(_Statement_QNAME, StatementType.class, null, value);
    }

}
