//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.13 at 10:45:44 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nvd.nist.gov/feeds/nvdcvestatements", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.csw.data.nvd.jaxb.vendorstatement;
