//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The ApplicablePlatformsType complex type specifies the languages, operating systems, architectures, and technologies in which a given weakness could appear. A technology represents a generally accepted feature of a system and often refers to a high-level functional component within a system. The required Prevalence attribute identifies the regularity with which the weakness is applicable to that platform. When providing an operating system name, an optional Common Platform Enumeration (CPE) identifier can be used to a identify a specific OS.
 * 
 * <p>Java class for ApplicablePlatformsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicablePlatformsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Language" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}LanguageNameEnumeration" />
 *                 &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}LanguageClassEnumeration" />
 *                 &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Operating_System" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}OperatingSystemNameEnumeration" />
 *                 &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CPE_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}OperatingSystemClassEnumeration" />
 *                 &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Architecture" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}ArchitectureNameEnumeration" />
 *                 &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}ArchitectureClassEnumeration" />
 *                 &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Technology" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}TechnologyNameEnumeration" />
 *                 &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}TechnologyClassEnumeration" />
 *                 &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicablePlatformsType", propOrder = {
    "language",
    "operatingSystem",
    "architecture",
    "technology"
})
public class ApplicablePlatformsType {

    @XmlElement(name = "Language")
    protected List<ApplicablePlatformsType.Language> language;
    @XmlElement(name = "Operating_System")
    protected List<ApplicablePlatformsType.OperatingSystem> operatingSystem;
    @XmlElement(name = "Architecture")
    protected List<ApplicablePlatformsType.Architecture> architecture;
    @XmlElement(name = "Technology")
    protected List<ApplicablePlatformsType.Technology> technology;

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicablePlatformsType.Language }
     * 
     * 
     */
    public List<ApplicablePlatformsType.Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<ApplicablePlatformsType.Language>();
        }
        return this.language;
    }

    /**
     * Gets the value of the operatingSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operatingSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperatingSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicablePlatformsType.OperatingSystem }
     * 
     * 
     */
    public List<ApplicablePlatformsType.OperatingSystem> getOperatingSystem() {
        if (operatingSystem == null) {
            operatingSystem = new ArrayList<ApplicablePlatformsType.OperatingSystem>();
        }
        return this.operatingSystem;
    }

    /**
     * Gets the value of the architecture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the architecture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchitecture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicablePlatformsType.Architecture }
     * 
     * 
     */
    public List<ApplicablePlatformsType.Architecture> getArchitecture() {
        if (architecture == null) {
            architecture = new ArrayList<ApplicablePlatformsType.Architecture>();
        }
        return this.architecture;
    }

    /**
     * Gets the value of the technology property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technology property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnology().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicablePlatformsType.Technology }
     * 
     * 
     */
    public List<ApplicablePlatformsType.Technology> getTechnology() {
        if (technology == null) {
            technology = new ArrayList<ApplicablePlatformsType.Technology>();
        }
        return this.technology;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}ArchitectureNameEnumeration" />
     *       &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}ArchitectureClassEnumeration" />
     *       &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Architecture {

        @XmlAttribute(name = "Name")
        protected ArchitectureNameEnumeration name;
        @XmlAttribute(name = "Class")
        protected ArchitectureClassEnumeration clazz;
        @XmlAttribute(name = "Prevalence", required = true)
        protected PrevalenceEnumeration prevalence;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link ArchitectureNameEnumeration }
         *     
         */
        public ArchitectureNameEnumeration getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArchitectureNameEnumeration }
         *     
         */
        public void setName(ArchitectureNameEnumeration value) {
            this.name = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link ArchitectureClassEnumeration }
         *     
         */
        public ArchitectureClassEnumeration getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArchitectureClassEnumeration }
         *     
         */
        public void setClazz(ArchitectureClassEnumeration value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the prevalence property.
         * 
         * @return
         *     possible object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public PrevalenceEnumeration getPrevalence() {
            return prevalence;
        }

        /**
         * Sets the value of the prevalence property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public void setPrevalence(PrevalenceEnumeration value) {
            this.prevalence = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}LanguageNameEnumeration" />
     *       &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}LanguageClassEnumeration" />
     *       &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Language {

        @XmlAttribute(name = "Name")
        protected String name;
        @XmlAttribute(name = "Class")
        protected LanguageClassEnumeration clazz;
        @XmlAttribute(name = "Prevalence", required = true)
        protected PrevalenceEnumeration prevalence;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link LanguageClassEnumeration }
         *     
         */
        public LanguageClassEnumeration getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link LanguageClassEnumeration }
         *     
         */
        public void setClazz(LanguageClassEnumeration value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the prevalence property.
         * 
         * @return
         *     possible object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public PrevalenceEnumeration getPrevalence() {
            return prevalence;
        }

        /**
         * Sets the value of the prevalence property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public void setPrevalence(PrevalenceEnumeration value) {
            this.prevalence = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}OperatingSystemNameEnumeration" />
     *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CPE_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}OperatingSystemClassEnumeration" />
     *       &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OperatingSystem {

        @XmlAttribute(name = "Name")
        protected OperatingSystemNameEnumeration name;
        @XmlAttribute(name = "Version")
        protected String version;
        @XmlAttribute(name = "CPE_ID")
        protected String cpeid;
        @XmlAttribute(name = "Class")
        protected OperatingSystemClassEnumeration clazz;
        @XmlAttribute(name = "Prevalence", required = true)
        protected PrevalenceEnumeration prevalence;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link OperatingSystemNameEnumeration }
         *     
         */
        public OperatingSystemNameEnumeration getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperatingSystemNameEnumeration }
         *     
         */
        public void setName(OperatingSystemNameEnumeration value) {
            this.name = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the cpeid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPEID() {
            return cpeid;
        }

        /**
         * Sets the value of the cpeid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPEID(String value) {
            this.cpeid = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link OperatingSystemClassEnumeration }
         *     
         */
        public OperatingSystemClassEnumeration getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link OperatingSystemClassEnumeration }
         *     
         */
        public void setClazz(OperatingSystemClassEnumeration value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the prevalence property.
         * 
         * @return
         *     possible object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public PrevalenceEnumeration getPrevalence() {
            return prevalence;
        }

        /**
         * Sets the value of the prevalence property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public void setPrevalence(PrevalenceEnumeration value) {
            this.prevalence = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Name" type="{http://cwe.mitre.org/cwe-6}TechnologyNameEnumeration" />
     *       &lt;attribute name="Class" type="{http://cwe.mitre.org/cwe-6}TechnologyClassEnumeration" />
     *       &lt;attribute name="Prevalence" use="required" type="{http://cwe.mitre.org/cwe-6}PrevalenceEnumeration" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Technology {

        @XmlAttribute(name = "Name")
        protected TechnologyNameEnumeration name;
        @XmlAttribute(name = "Class")
        protected TechnologyClassEnumeration clazz;
        @XmlAttribute(name = "Prevalence", required = true)
        protected PrevalenceEnumeration prevalence;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link TechnologyNameEnumeration }
         *     
         */
        public TechnologyNameEnumeration getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link TechnologyNameEnumeration }
         *     
         */
        public void setName(TechnologyNameEnumeration value) {
            this.name = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link TechnologyClassEnumeration }
         *     
         */
        public TechnologyClassEnumeration getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link TechnologyClassEnumeration }
         *     
         */
        public void setClazz(TechnologyClassEnumeration value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the prevalence property.
         * 
         * @return
         *     possible object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public PrevalenceEnumeration getPrevalence() {
            return prevalence;
        }

        /**
         * Sets the value of the prevalence property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrevalenceEnumeration }
         *     
         */
        public void setPrevalence(PrevalenceEnumeration value) {
            this.prevalence = value;
        }

    }

}
