//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetectionEffectivenessEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DetectionEffectivenessEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="High"/>
 *     &lt;enumeration value="Moderate"/>
 *     &lt;enumeration value="SOAR Partial"/>
 *     &lt;enumeration value="Opportunistic"/>
 *     &lt;enumeration value="Limited"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DetectionEffectivenessEnumeration")
@XmlEnum
public enum DetectionEffectivenessEnumeration {

    @XmlEnumValue("High")
    HIGH("High"),
    @XmlEnumValue("Moderate")
    MODERATE("Moderate"),
    @XmlEnumValue("SOAR Partial")
    SOAR_PARTIAL("SOAR Partial"),
    @XmlEnumValue("Opportunistic")
    OPPORTUNISTIC("Opportunistic"),
    @XmlEnumValue("Limited")
    LIMITED("Limited"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    DetectionEffectivenessEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DetectionEffectivenessEnumeration fromValue(String v) {
        for (DetectionEffectivenessEnumeration c: DetectionEffectivenessEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
