//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The optional Detection_Method_ID attribute is used by the internal CWE team to uniquely identify methods that are repeated across any number of individual weaknesses. To help make sure that the details of these common methods stay synchronized, the Detection_Method_ID is used to quickly identify those Detection_Method elements across CWE that should be identical. The identifier is a string and should match the following format: DM-1.
 * 
 * <p>Java class for DetectionMethodsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetectionMethodsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Detection_Method" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Method" type="{http://cwe.mitre.org/cwe-6}DetectionMethodEnumeration"/>
 *                   &lt;element name="Description" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
 *                   &lt;element name="Effectiveness" type="{http://cwe.mitre.org/cwe-6}DetectionEffectivenessEnumeration" minOccurs="0"/>
 *                   &lt;element name="Effectiveness_Notes" type="{http://cwe.mitre.org/cwe-6}StructuredTextType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Detection_Method_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetectionMethodsType", propOrder = {
    "detectionMethod"
})
public class DetectionMethodsType {

    @XmlElement(name = "Detection_Method", required = true)
    protected List<DetectionMethodsType.DetectionMethod> detectionMethod;

    /**
     * Gets the value of the detectionMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detectionMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetectionMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetectionMethodsType.DetectionMethod }
     * 
     * 
     */
    public List<DetectionMethodsType.DetectionMethod> getDetectionMethod() {
        if (detectionMethod == null) {
            detectionMethod = new ArrayList<DetectionMethodsType.DetectionMethod>();
        }
        return this.detectionMethod;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Method" type="{http://cwe.mitre.org/cwe-6}DetectionMethodEnumeration"/>
     *         &lt;element name="Description" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
     *         &lt;element name="Effectiveness" type="{http://cwe.mitre.org/cwe-6}DetectionEffectivenessEnumeration" minOccurs="0"/>
     *         &lt;element name="Effectiveness_Notes" type="{http://cwe.mitre.org/cwe-6}StructuredTextType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Detection_Method_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "method",
        "description",
        "effectiveness",
        "effectivenessNotes"
    })
    public static class DetectionMethod {

        @XmlElement(name = "Method", required = true)
        @XmlSchemaType(name = "string")
        protected DetectionMethodEnumeration method;
        @XmlElement(name = "Description", required = true)
        protected StructuredTextType description;
        @XmlElement(name = "Effectiveness")
        @XmlSchemaType(name = "string")
        protected DetectionEffectivenessEnumeration effectiveness;
        @XmlElement(name = "Effectiveness_Notes")
        protected StructuredTextType effectivenessNotes;
        @XmlAttribute(name = "Detection_Method_ID")
        protected String detectionMethodID;

        /**
         * Gets the value of the method property.
         * 
         * @return
         *     possible object is
         *     {@link DetectionMethodEnumeration }
         *     
         */
        public DetectionMethodEnumeration getMethod() {
            return method;
        }

        /**
         * Sets the value of the method property.
         * 
         * @param value
         *     allowed object is
         *     {@link DetectionMethodEnumeration }
         *     
         */
        public void setMethod(DetectionMethodEnumeration value) {
            this.method = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredTextType }
         *     
         */
        public StructuredTextType getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredTextType }
         *     
         */
        public void setDescription(StructuredTextType value) {
            this.description = value;
        }

        /**
         * Gets the value of the effectiveness property.
         * 
         * @return
         *     possible object is
         *     {@link DetectionEffectivenessEnumeration }
         *     
         */
        public DetectionEffectivenessEnumeration getEffectiveness() {
            return effectiveness;
        }

        /**
         * Sets the value of the effectiveness property.
         * 
         * @param value
         *     allowed object is
         *     {@link DetectionEffectivenessEnumeration }
         *     
         */
        public void setEffectiveness(DetectionEffectivenessEnumeration value) {
            this.effectiveness = value;
        }

        /**
         * Gets the value of the effectivenessNotes property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredTextType }
         *     
         */
        public StructuredTextType getEffectivenessNotes() {
            return effectivenessNotes;
        }

        /**
         * Sets the value of the effectivenessNotes property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredTextType }
         *     
         */
        public void setEffectivenessNotes(StructuredTextType value) {
            this.effectivenessNotes = value;
        }

        /**
         * Gets the value of the detectionMethodID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDetectionMethodID() {
            return detectionMethodID;
        }

        /**
         * Sets the value of the detectionMethodID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDetectionMethodID(String value) {
            this.detectionMethodID = value;
        }

    }

}
