//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NoteTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NoteTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Applicable Platform"/>
 *     &lt;enumeration value="Maintenance"/>
 *     &lt;enumeration value="Relationship"/>
 *     &lt;enumeration value="Research Gap"/>
 *     &lt;enumeration value="Terminology"/>
 *     &lt;enumeration value="Theoretical"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NoteTypeEnumeration")
@XmlEnum
public enum NoteTypeEnumeration {

    @XmlEnumValue("Applicable Platform")
    APPLICABLE_PLATFORM("Applicable Platform"),
    @XmlEnumValue("Maintenance")
    MAINTENANCE("Maintenance"),
    @XmlEnumValue("Relationship")
    RELATIONSHIP("Relationship"),
    @XmlEnumValue("Research Gap")
    RESEARCH_GAP("Research Gap"),
    @XmlEnumValue("Terminology")
    TERMINOLOGY("Terminology"),
    @XmlEnumValue("Theoretical")
    THEORETICAL("Theoretical"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    NoteTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NoteTypeEnumeration fromValue(String v) {
        for (NoteTypeEnumeration c: NoteTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
