//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.csw.data.nvd.jaxb.cwe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentHistoryTypeSubmissionSubmissionDate_QNAME = new QName("http://cwe.mitre.org/cwe-6", "Submission_Date");
    private final static QName _ContentHistoryTypeSubmissionSubmissionName_QNAME = new QName("http://cwe.mitre.org/cwe-6", "Submission_Name");
    private final static QName _ContentHistoryTypeSubmissionSubmissionOrganization_QNAME = new QName("http://cwe.mitre.org/cwe-6", "Submission_Organization");
    private final static QName _ContentHistoryTypeSubmissionSubmissionComment_QNAME = new QName("http://cwe.mitre.org/cwe-6", "Submission_Comment");
    private final static QName _RelationshipsTypeMemberOf_QNAME = new QName("http://cwe.mitre.org/cwe-6", "Member_Of");
    private final static QName _RelationshipsTypeHasMember_QNAME = new QName("http://cwe.mitre.org/cwe-6", "Has_Member");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.csw.data.nvd.jaxb.cwe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WeaknessCatalog }
     * 
     */
    public WeaknessCatalog createWeaknessCatalog() {
        return new WeaknessCatalog();
    }

    /**
     * Create an instance of {@link ContentHistoryType }
     * 
     */
    public ContentHistoryType createContentHistoryType() {
        return new ContentHistoryType();
    }

    /**
     * Create an instance of {@link ModesOfIntroductionType }
     * 
     */
    public ModesOfIntroductionType createModesOfIntroductionType() {
        return new ModesOfIntroductionType();
    }

    /**
     * Create an instance of {@link NotesType }
     * 
     */
    public NotesType createNotesType() {
        return new NotesType();
    }

    /**
     * Create an instance of {@link WeaknessOrdinalitiesType }
     * 
     */
    public WeaknessOrdinalitiesType createWeaknessOrdinalitiesType() {
        return new WeaknessOrdinalitiesType();
    }

    /**
     * Create an instance of {@link ObservedExampleType }
     * 
     */
    public ObservedExampleType createObservedExampleType() {
        return new ObservedExampleType();
    }

    /**
     * Create an instance of {@link DemonstrativeExamplesType }
     * 
     */
    public DemonstrativeExamplesType createDemonstrativeExamplesType() {
        return new DemonstrativeExamplesType();
    }

    /**
     * Create an instance of {@link PotentialMitigationsType }
     * 
     */
    public PotentialMitigationsType createPotentialMitigationsType() {
        return new PotentialMitigationsType();
    }

    /**
     * Create an instance of {@link TaxonomyMappingsType }
     * 
     */
    public TaxonomyMappingsType createTaxonomyMappingsType() {
        return new TaxonomyMappingsType();
    }

    /**
     * Create an instance of {@link AudienceType }
     * 
     */
    public AudienceType createAudienceType() {
        return new AudienceType();
    }

    /**
     * Create an instance of {@link RelatedWeaknessesType }
     * 
     */
    public RelatedWeaknessesType createRelatedWeaknessesType() {
        return new RelatedWeaknessesType();
    }

    /**
     * Create an instance of {@link CommonConsequencesType }
     * 
     */
    public CommonConsequencesType createCommonConsequencesType() {
        return new CommonConsequencesType();
    }

    /**
     * Create an instance of {@link ApplicablePlatformsType }
     * 
     */
    public ApplicablePlatformsType createApplicablePlatformsType() {
        return new ApplicablePlatformsType();
    }

    /**
     * Create an instance of {@link RelatedAttackPatternsType }
     * 
     */
    public RelatedAttackPatternsType createRelatedAttackPatternsType() {
        return new RelatedAttackPatternsType();
    }

    /**
     * Create an instance of {@link DetectionMethodsType }
     * 
     */
    public DetectionMethodsType createDetectionMethodsType() {
        return new DetectionMethodsType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link AlternateTermsType }
     * 
     */
    public AlternateTermsType createAlternateTermsType() {
        return new AlternateTermsType();
    }

    /**
     * Create an instance of {@link WeaknessCatalog.Weaknesses }
     * 
     */
    public WeaknessCatalog.Weaknesses createWeaknessCatalogWeaknesses() {
        return new WeaknessCatalog.Weaknesses();
    }

    /**
     * Create an instance of {@link WeaknessCatalog.Categories }
     * 
     */
    public WeaknessCatalog.Categories createWeaknessCatalogCategories() {
        return new WeaknessCatalog.Categories();
    }

    /**
     * Create an instance of {@link WeaknessCatalog.Views }
     * 
     */
    public WeaknessCatalog.Views createWeaknessCatalogViews() {
        return new WeaknessCatalog.Views();
    }

    /**
     * Create an instance of {@link WeaknessCatalog.ExternalReferences }
     * 
     */
    public WeaknessCatalog.ExternalReferences createWeaknessCatalogExternalReferences() {
        return new WeaknessCatalog.ExternalReferences();
    }

    /**
     * Create an instance of {@link AffectedResourcesType }
     * 
     */
    public AffectedResourcesType createAffectedResourcesType() {
        return new AffectedResourcesType();
    }

    /**
     * Create an instance of {@link BackgroundDetailsType }
     * 
     */
    public BackgroundDetailsType createBackgroundDetailsType() {
        return new BackgroundDetailsType();
    }

    /**
     * Create an instance of {@link WeaknessType }
     * 
     */
    public WeaknessType createWeaknessType() {
        return new WeaknessType();
    }

    /**
     * Create an instance of {@link ExternalReferenceType }
     * 
     */
    public ExternalReferenceType createExternalReferenceType() {
        return new ExternalReferenceType();
    }

    /**
     * Create an instance of {@link FunctionalAreasType }
     * 
     */
    public FunctionalAreasType createFunctionalAreasType() {
        return new FunctionalAreasType();
    }

    /**
     * Create an instance of {@link RelationshipsType }
     * 
     */
    public RelationshipsType createRelationshipsType() {
        return new RelationshipsType();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link StructuredCodeType }
     * 
     */
    public StructuredCodeType createStructuredCodeType() {
        return new StructuredCodeType();
    }

    /**
     * Create an instance of {@link ExploitationFactorsType }
     * 
     */
    public ExploitationFactorsType createExploitationFactorsType() {
        return new ExploitationFactorsType();
    }

    /**
     * Create an instance of {@link StructuredTextType }
     * 
     */
    public StructuredTextType createStructuredTextType() {
        return new StructuredTextType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link ContentHistoryType.Submission }
     * 
     */
    public ContentHistoryType.Submission createContentHistoryTypeSubmission() {
        return new ContentHistoryType.Submission();
    }

    /**
     * Create an instance of {@link ContentHistoryType.Modification }
     * 
     */
    public ContentHistoryType.Modification createContentHistoryTypeModification() {
        return new ContentHistoryType.Modification();
    }

    /**
     * Create an instance of {@link ContentHistoryType.Contribution }
     * 
     */
    public ContentHistoryType.Contribution createContentHistoryTypeContribution() {
        return new ContentHistoryType.Contribution();
    }

    /**
     * Create an instance of {@link ContentHistoryType.PreviousEntryName }
     * 
     */
    public ContentHistoryType.PreviousEntryName createContentHistoryTypePreviousEntryName() {
        return new ContentHistoryType.PreviousEntryName();
    }

    /**
     * Create an instance of {@link ModesOfIntroductionType.Introduction }
     * 
     */
    public ModesOfIntroductionType.Introduction createModesOfIntroductionTypeIntroduction() {
        return new ModesOfIntroductionType.Introduction();
    }

    /**
     * Create an instance of {@link NotesType.Note }
     * 
     */
    public NotesType.Note createNotesTypeNote() {
        return new NotesType.Note();
    }

    /**
     * Create an instance of {@link WeaknessOrdinalitiesType.WeaknessOrdinality }
     * 
     */
    public WeaknessOrdinalitiesType.WeaknessOrdinality createWeaknessOrdinalitiesTypeWeaknessOrdinality() {
        return new WeaknessOrdinalitiesType.WeaknessOrdinality();
    }

    /**
     * Create an instance of {@link ObservedExampleType.ObservedExample }
     * 
     */
    public ObservedExampleType.ObservedExample createObservedExampleTypeObservedExample() {
        return new ObservedExampleType.ObservedExample();
    }

    /**
     * Create an instance of {@link DemonstrativeExamplesType.DemonstrativeExample }
     * 
     */
    public DemonstrativeExamplesType.DemonstrativeExample createDemonstrativeExamplesTypeDemonstrativeExample() {
        return new DemonstrativeExamplesType.DemonstrativeExample();
    }

    /**
     * Create an instance of {@link PotentialMitigationsType.Mitigation }
     * 
     */
    public PotentialMitigationsType.Mitigation createPotentialMitigationsTypeMitigation() {
        return new PotentialMitigationsType.Mitigation();
    }

    /**
     * Create an instance of {@link TaxonomyMappingsType.TaxonomyMapping }
     * 
     */
    public TaxonomyMappingsType.TaxonomyMapping createTaxonomyMappingsTypeTaxonomyMapping() {
        return new TaxonomyMappingsType.TaxonomyMapping();
    }

    /**
     * Create an instance of {@link AudienceType.Stakeholder }
     * 
     */
    public AudienceType.Stakeholder createAudienceTypeStakeholder() {
        return new AudienceType.Stakeholder();
    }

    /**
     * Create an instance of {@link RelatedWeaknessesType.RelatedWeakness }
     * 
     */
    public RelatedWeaknessesType.RelatedWeakness createRelatedWeaknessesTypeRelatedWeakness() {
        return new RelatedWeaknessesType.RelatedWeakness();
    }

    /**
     * Create an instance of {@link CommonConsequencesType.Consequence }
     * 
     */
    public CommonConsequencesType.Consequence createCommonConsequencesTypeConsequence() {
        return new CommonConsequencesType.Consequence();
    }

    /**
     * Create an instance of {@link ApplicablePlatformsType.Language }
     * 
     */
    public ApplicablePlatformsType.Language createApplicablePlatformsTypeLanguage() {
        return new ApplicablePlatformsType.Language();
    }

    /**
     * Create an instance of {@link ApplicablePlatformsType.OperatingSystem }
     * 
     */
    public ApplicablePlatformsType.OperatingSystem createApplicablePlatformsTypeOperatingSystem() {
        return new ApplicablePlatformsType.OperatingSystem();
    }

    /**
     * Create an instance of {@link ApplicablePlatformsType.Architecture }
     * 
     */
    public ApplicablePlatformsType.Architecture createApplicablePlatformsTypeArchitecture() {
        return new ApplicablePlatformsType.Architecture();
    }

    /**
     * Create an instance of {@link ApplicablePlatformsType.Technology }
     * 
     */
    public ApplicablePlatformsType.Technology createApplicablePlatformsTypeTechnology() {
        return new ApplicablePlatformsType.Technology();
    }

    /**
     * Create an instance of {@link RelatedAttackPatternsType.RelatedAttackPattern }
     * 
     */
    public RelatedAttackPatternsType.RelatedAttackPattern createRelatedAttackPatternsTypeRelatedAttackPattern() {
        return new RelatedAttackPatternsType.RelatedAttackPattern();
    }

    /**
     * Create an instance of {@link DetectionMethodsType.DetectionMethod }
     * 
     */
    public DetectionMethodsType.DetectionMethod createDetectionMethodsTypeDetectionMethod() {
        return new DetectionMethodsType.DetectionMethod();
    }

    /**
     * Create an instance of {@link ReferencesType.Reference }
     * 
     */
    public ReferencesType.Reference createReferencesTypeReference() {
        return new ReferencesType.Reference();
    }

    /**
     * Create an instance of {@link AlternateTermsType.AlternateTerm }
     * 
     */
    public AlternateTermsType.AlternateTerm createAlternateTermsTypeAlternateTerm() {
        return new AlternateTermsType.AlternateTerm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cwe.mitre.org/cwe-6", name = "Submission_Date", scope = ContentHistoryType.Submission.class)
    public JAXBElement<XMLGregorianCalendar> createContentHistoryTypeSubmissionSubmissionDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ContentHistoryTypeSubmissionSubmissionDate_QNAME, XMLGregorianCalendar.class, ContentHistoryType.Submission.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cwe.mitre.org/cwe-6", name = "Submission_Name", scope = ContentHistoryType.Submission.class)
    public JAXBElement<String> createContentHistoryTypeSubmissionSubmissionName(String value) {
        return new JAXBElement<String>(_ContentHistoryTypeSubmissionSubmissionName_QNAME, String.class, ContentHistoryType.Submission.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cwe.mitre.org/cwe-6", name = "Submission_Organization", scope = ContentHistoryType.Submission.class)
    public JAXBElement<String> createContentHistoryTypeSubmissionSubmissionOrganization(String value) {
        return new JAXBElement<String>(_ContentHistoryTypeSubmissionSubmissionOrganization_QNAME, String.class, ContentHistoryType.Submission.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cwe.mitre.org/cwe-6", name = "Submission_Comment", scope = ContentHistoryType.Submission.class)
    public JAXBElement<String> createContentHistoryTypeSubmissionSubmissionComment(String value) {
        return new JAXBElement<String>(_ContentHistoryTypeSubmissionSubmissionComment_QNAME, String.class, ContentHistoryType.Submission.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MemberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cwe.mitre.org/cwe-6", name = "Member_Of", scope = RelationshipsType.class)
    public JAXBElement<MemberType> createRelationshipsTypeMemberOf(MemberType value) {
        return new JAXBElement<MemberType>(_RelationshipsTypeMemberOf_QNAME, MemberType.class, RelationshipsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MemberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cwe.mitre.org/cwe-6", name = "Has_Member", scope = RelationshipsType.class)
    public JAXBElement<MemberType> createRelationshipsTypeHasMember(MemberType value) {
        return new JAXBElement<MemberType>(_RelationshipsTypeHasMember_QNAME, MemberType.class, RelationshipsType.class, value);
    }

}
