//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperatingSystemNameEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperatingSystemNameEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AIX"/>
 *     &lt;enumeration value="Android"/>
 *     &lt;enumeration value="BlackBerry OS"/>
 *     &lt;enumeration value="Chrome OS"/>
 *     &lt;enumeration value="Darwin"/>
 *     &lt;enumeration value="FreeBSD"/>
 *     &lt;enumeration value="iOS"/>
 *     &lt;enumeration value="macOS"/>
 *     &lt;enumeration value="NetBSD"/>
 *     &lt;enumeration value="OpenBSD"/>
 *     &lt;enumeration value="Red Hat"/>
 *     &lt;enumeration value="Solaris"/>
 *     &lt;enumeration value="SUSE"/>
 *     &lt;enumeration value="tvOS"/>
 *     &lt;enumeration value="Ubuntu"/>
 *     &lt;enumeration value="watchOS"/>
 *     &lt;enumeration value="Windows 9x"/>
 *     &lt;enumeration value="Windows Embedded"/>
 *     &lt;enumeration value="Windows NT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OperatingSystemNameEnumeration")
@XmlEnum
public enum OperatingSystemNameEnumeration {

    AIX("AIX"),
    @XmlEnumValue("Android")
    ANDROID("Android"),
    @XmlEnumValue("BlackBerry OS")
    BLACK_BERRY_OS("BlackBerry OS"),
    @XmlEnumValue("Chrome OS")
    CHROME_OS("Chrome OS"),
    @XmlEnumValue("Darwin")
    DARWIN("Darwin"),
    @XmlEnumValue("FreeBSD")
    FREE_BSD("FreeBSD"),
    @XmlEnumValue("iOS")
    I_OS("iOS"),
    @XmlEnumValue("macOS")
    MAC_OS("macOS"),
    @XmlEnumValue("NetBSD")
    NET_BSD("NetBSD"),
    @XmlEnumValue("OpenBSD")
    OPEN_BSD("OpenBSD"),
    @XmlEnumValue("Red Hat")
    RED_HAT("Red Hat"),
    @XmlEnumValue("Solaris")
    SOLARIS("Solaris"),
    SUSE("SUSE"),
    @XmlEnumValue("tvOS")
    TV_OS("tvOS"),
    @XmlEnumValue("Ubuntu")
    UBUNTU("Ubuntu"),
    @XmlEnumValue("watchOS")
    WATCH_OS("watchOS"),
    @XmlEnumValue("Windows 9x")
    WINDOWS_9_X("Windows 9x"),
    @XmlEnumValue("Windows Embedded")
    WINDOWS_EMBEDDED("Windows Embedded"),
    @XmlEnumValue("Windows NT")
    WINDOWS_NT("Windows NT");
    private final String value;

    OperatingSystemNameEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperatingSystemNameEnumeration fromValue(String v) {
        for (OperatingSystemNameEnumeration c: OperatingSystemNameEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
