//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperatingSystemClassEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperatingSystemClassEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Linux"/>
 *     &lt;enumeration value="macOS"/>
 *     &lt;enumeration value="Unix"/>
 *     &lt;enumeration value="Windows"/>
 *     &lt;enumeration value="OS-Independent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OperatingSystemClassEnumeration")
@XmlEnum
public enum OperatingSystemClassEnumeration {

    @XmlEnumValue("Linux")
    LINUX("Linux"),
    @XmlEnumValue("macOS")
    MAC_OS("macOS"),
    @XmlEnumValue("Unix")
    UNIX("Unix"),
    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("OS-Independent")
    OS_INDEPENDENT("OS-Independent");
    private final String value;

    OperatingSystemClassEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperatingSystemClassEnumeration fromValue(String v) {
        for (OperatingSystemClassEnumeration c: OperatingSystemClassEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
