//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The RelatedWeaknessesType complex type is used to refer to other weaknesses that differ only in their level of abstraction. It contains one or more Related_Weakness elements, each of which is used to link to the CWE identifier of the other Weakness. The nature of the relation is captured by the Nature attribute. Please see the RelatedNatureEnumeration simple type definition for details about the valid value and meanings. The optional Chain_ID attribute specifies the unique ID of a named chain that a CanFollow or CanPrecede relationship pertains to. The optional Ordinal attribute is used to determine if this relationship is the primary ChildOf relationship for this weakness for a given View_ID. This attribute can only have the value "Primary" and should only be included for the primary parent/child relationship. For each unique triple of <Nature, CWE_ID, View_ID>, there should be only one relationship that is given a "Primary" ordinal.
 * 
 * <p>Java class for RelatedWeaknessesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedWeaknessesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Related_Weakness" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Nature" use="required" type="{http://cwe.mitre.org/cwe-6}RelatedNatureEnumeration" />
 *                 &lt;attribute name="CWE_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="View_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="Chain_ID" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="Ordinal" type="{http://cwe.mitre.org/cwe-6}OrdinalEnumeration" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedWeaknessesType", propOrder = {
    "relatedWeakness"
})
public class RelatedWeaknessesType {

    @XmlElement(name = "Related_Weakness", required = true)
    protected List<RelatedWeaknessesType.RelatedWeakness> relatedWeakness;

    /**
     * Gets the value of the relatedWeakness property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedWeakness property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedWeakness().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedWeaknessesType.RelatedWeakness }
     * 
     * 
     */
    public List<RelatedWeaknessesType.RelatedWeakness> getRelatedWeakness() {
        if (relatedWeakness == null) {
            relatedWeakness = new ArrayList<RelatedWeaknessesType.RelatedWeakness>();
        }
        return this.relatedWeakness;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Nature" use="required" type="{http://cwe.mitre.org/cwe-6}RelatedNatureEnumeration" />
     *       &lt;attribute name="CWE_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="View_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="Chain_ID" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="Ordinal" type="{http://cwe.mitre.org/cwe-6}OrdinalEnumeration" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RelatedWeakness {

        @XmlAttribute(name = "Nature", required = true)
        protected RelatedNatureEnumeration nature;
        @XmlAttribute(name = "CWE_ID", required = true)
        protected BigInteger cweid;
        @XmlAttribute(name = "View_ID", required = true)
        protected BigInteger viewID;
        @XmlAttribute(name = "Chain_ID")
        protected BigInteger chainID;
        @XmlAttribute(name = "Ordinal")
        protected OrdinalEnumeration ordinal;

        /**
         * Gets the value of the nature property.
         * 
         * @return
         *     possible object is
         *     {@link RelatedNatureEnumeration }
         *     
         */
        public RelatedNatureEnumeration getNature() {
            return nature;
        }

        /**
         * Sets the value of the nature property.
         * 
         * @param value
         *     allowed object is
         *     {@link RelatedNatureEnumeration }
         *     
         */
        public void setNature(RelatedNatureEnumeration value) {
            this.nature = value;
        }

        /**
         * Gets the value of the cweid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCWEID() {
            return cweid;
        }

        /**
         * Sets the value of the cweid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCWEID(BigInteger value) {
            this.cweid = value;
        }

        /**
         * Gets the value of the viewID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getViewID() {
            return viewID;
        }

        /**
         * Sets the value of the viewID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setViewID(BigInteger value) {
            this.viewID = value;
        }

        /**
         * Gets the value of the chainID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getChainID() {
            return chainID;
        }

        /**
         * Sets the value of the chainID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setChainID(BigInteger value) {
            this.chainID = value;
        }

        /**
         * Gets the value of the ordinal property.
         * 
         * @return
         *     possible object is
         *     {@link OrdinalEnumeration }
         *     
         */
        public OrdinalEnumeration getOrdinal() {
            return ordinal;
        }

        /**
         * Sets the value of the ordinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrdinalEnumeration }
         *     
         */
        public void setOrdinal(OrdinalEnumeration value) {
            this.ordinal = value;
        }

    }

}
