//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResourceEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CPU"/>
 *     &lt;enumeration value="File or Directory"/>
 *     &lt;enumeration value="Memory"/>
 *     &lt;enumeration value="System Process"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResourceEnumeration")
@XmlEnum
public enum ResourceEnumeration {

    CPU("CPU"),
    @XmlEnumValue("File or Directory")
    FILE_OR_DIRECTORY("File or Directory"),
    @XmlEnumValue("Memory")
    MEMORY("Memory"),
    @XmlEnumValue("System Process")
    SYSTEM_PROCESS("System Process"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ResourceEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResourceEnumeration fromValue(String v) {
        for (ResourceEnumeration c: ResourceEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
