//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.jaxb.cwe;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The required ID attribute provides a unique identifier for the entry. It is considered static for the lifetime of the entry. If this entry becomes deprecated, the identifier will not be reused. The required Name attribute is a string that identifies the entry. The name should focus on the weakness being described and should avoid mentioning the attack that exploits the weakness or the consequences of exploiting the weakness. All words in the entry name should be capitalized except for articles and prepositions, unless they begin or end the name. Subsequent words in a hyphenated chain are also not capitalized. The required Abstraction attribute defines the abstraction level for this weakness. The required Structure attribute defines the structural nature of the weakness. The required Status attribute defines the maturity of the information for this weakness.
 * 
 * <p>Java class for WeaknessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeaknessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Extended_Description" type="{http://cwe.mitre.org/cwe-6}StructuredTextType" minOccurs="0"/>
 *         &lt;element name="Related_Weaknesses" type="{http://cwe.mitre.org/cwe-6}RelatedWeaknessesType" minOccurs="0"/>
 *         &lt;element name="Weakness_Ordinalities" type="{http://cwe.mitre.org/cwe-6}WeaknessOrdinalitiesType" minOccurs="0"/>
 *         &lt;element name="Applicable_Platforms" type="{http://cwe.mitre.org/cwe-6}ApplicablePlatformsType" minOccurs="0"/>
 *         &lt;element name="Background_Details" type="{http://cwe.mitre.org/cwe-6}BackgroundDetailsType" minOccurs="0"/>
 *         &lt;element name="Alternate_Terms" type="{http://cwe.mitre.org/cwe-6}AlternateTermsType" minOccurs="0"/>
 *         &lt;element name="Modes_Of_Introduction" type="{http://cwe.mitre.org/cwe-6}ModesOfIntroductionType" minOccurs="0"/>
 *         &lt;element name="Exploitation_Factors" type="{http://cwe.mitre.org/cwe-6}ExploitationFactorsType" minOccurs="0"/>
 *         &lt;element name="Likelihood_Of_Exploit" type="{http://cwe.mitre.org/cwe-6}LikelihoodEnumeration" minOccurs="0"/>
 *         &lt;element name="Common_Consequences" type="{http://cwe.mitre.org/cwe-6}CommonConsequencesType" minOccurs="0"/>
 *         &lt;element name="Detection_Methods" type="{http://cwe.mitre.org/cwe-6}DetectionMethodsType" minOccurs="0"/>
 *         &lt;element name="Potential_Mitigations" type="{http://cwe.mitre.org/cwe-6}PotentialMitigationsType" minOccurs="0"/>
 *         &lt;element name="Demonstrative_Examples" type="{http://cwe.mitre.org/cwe-6}DemonstrativeExamplesType" minOccurs="0"/>
 *         &lt;element name="Observed_Examples" type="{http://cwe.mitre.org/cwe-6}ObservedExampleType" minOccurs="0"/>
 *         &lt;element name="Functional_Areas" type="{http://cwe.mitre.org/cwe-6}FunctionalAreasType" minOccurs="0"/>
 *         &lt;element name="Affected_Resources" type="{http://cwe.mitre.org/cwe-6}AffectedResourcesType" minOccurs="0"/>
 *         &lt;element name="Taxonomy_Mappings" type="{http://cwe.mitre.org/cwe-6}TaxonomyMappingsType" minOccurs="0"/>
 *         &lt;element name="Related_Attack_Patterns" type="{http://cwe.mitre.org/cwe-6}RelatedAttackPatternsType" minOccurs="0"/>
 *         &lt;element name="References" type="{http://cwe.mitre.org/cwe-6}ReferencesType" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://cwe.mitre.org/cwe-6}NotesType" minOccurs="0"/>
 *         &lt;element name="Content_History" type="{http://cwe.mitre.org/cwe-6}ContentHistoryType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Abstraction" use="required" type="{http://cwe.mitre.org/cwe-6}AbstractionEnumeration" />
 *       &lt;attribute name="Structure" use="required" type="{http://cwe.mitre.org/cwe-6}StructureEnumeration" />
 *       &lt;attribute name="Status" use="required" type="{http://cwe.mitre.org/cwe-6}StatusEnumeration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Weakness")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeaknessType", propOrder = {
    "description",
    "extendedDescription",
    "relatedWeaknesses",
    "weaknessOrdinalities",
    "applicablePlatforms",
    "backgroundDetails",
    "alternateTerms",
    "modesOfIntroduction",
    "exploitationFactors",
    "likelihoodOfExploit",
    "commonConsequences",
    "detectionMethods",
    "potentialMitigations",
    "demonstrativeExamples",
    "observedExamples",
    "functionalAreas",
    "affectedResources",
    "taxonomyMappings",
    "relatedAttackPatterns",
    "references",
    "notes",
    "contentHistory"
})
public class WeaknessType {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Extended_Description")
    protected StructuredTextType extendedDescription;
    @XmlElement(name = "Related_Weaknesses")
    protected RelatedWeaknessesType relatedWeaknesses;
    @XmlElement(name = "Weakness_Ordinalities")
    protected WeaknessOrdinalitiesType weaknessOrdinalities;
    @XmlElement(name = "Applicable_Platforms")
    protected ApplicablePlatformsType applicablePlatforms;
    @XmlElement(name = "Background_Details")
    protected BackgroundDetailsType backgroundDetails;
    @XmlElement(name = "Alternate_Terms")
    protected AlternateTermsType alternateTerms;
    @XmlElement(name = "Modes_Of_Introduction")
    protected ModesOfIntroductionType modesOfIntroduction;
    @XmlElement(name = "Exploitation_Factors")
    protected ExploitationFactorsType exploitationFactors;
    @XmlElement(name = "Likelihood_Of_Exploit")
    @XmlSchemaType(name = "string")
    protected LikelihoodEnumeration likelihoodOfExploit;
    @XmlElement(name = "Common_Consequences")
    protected CommonConsequencesType commonConsequences;
    @XmlElement(name = "Detection_Methods")
    protected DetectionMethodsType detectionMethods;
    @XmlElement(name = "Potential_Mitigations")
    protected PotentialMitigationsType potentialMitigations;
    @XmlElement(name = "Demonstrative_Examples")
    protected DemonstrativeExamplesType demonstrativeExamples;
    @XmlElement(name = "Observed_Examples")
    protected ObservedExampleType observedExamples;
    @XmlElement(name = "Functional_Areas")
    protected FunctionalAreasType functionalAreas;
    @XmlElement(name = "Affected_Resources")
    protected AffectedResourcesType affectedResources;
    @XmlElement(name = "Taxonomy_Mappings")
    protected TaxonomyMappingsType taxonomyMappings;
    @XmlElement(name = "Related_Attack_Patterns")
    protected RelatedAttackPatternsType relatedAttackPatterns;
    @XmlElement(name = "References")
    protected ReferencesType references;
    @XmlElement(name = "Notes")
    protected NotesType notes;
    @XmlElement(name = "Content_History")
    protected ContentHistoryType contentHistory;
    @XmlAttribute(name = "ID", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Abstraction", required = true)
    protected AbstractionEnumeration abstraction;
    @XmlAttribute(name = "Structure", required = true)
    protected StructureEnumeration structure;
    @XmlAttribute(name = "Status", required = true)
    protected StatusEnumeration status;
    

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the extendedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredTextType }
     *     
     */
    public StructuredTextType getExtendedDescription() {
        return extendedDescription;
    }

    /**
     * Sets the value of the extendedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredTextType }
     *     
     */
    public void setExtendedDescription(StructuredTextType value) {
        this.extendedDescription = value;
    }

    /**
     * Gets the value of the relatedWeaknesses property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedWeaknessesType }
     *     
     */
    public RelatedWeaknessesType getRelatedWeaknesses() {
        return relatedWeaknesses;
    }

    /**
     * Sets the value of the relatedWeaknesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedWeaknessesType }
     *     
     */
    public void setRelatedWeaknesses(RelatedWeaknessesType value) {
        this.relatedWeaknesses = value;
    }

    /**
     * Gets the value of the weaknessOrdinalities property.
     * 
     * @return
     *     possible object is
     *     {@link WeaknessOrdinalitiesType }
     *     
     */
    public WeaknessOrdinalitiesType getWeaknessOrdinalities() {
        return weaknessOrdinalities;
    }

    /**
     * Sets the value of the weaknessOrdinalities property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeaknessOrdinalitiesType }
     *     
     */
    public void setWeaknessOrdinalities(WeaknessOrdinalitiesType value) {
        this.weaknessOrdinalities = value;
    }

    /**
     * Gets the value of the applicablePlatforms property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicablePlatformsType }
     *     
     */
    public ApplicablePlatformsType getApplicablePlatforms() {
        return applicablePlatforms;
    }

    /**
     * Sets the value of the applicablePlatforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicablePlatformsType }
     *     
     */
    public void setApplicablePlatforms(ApplicablePlatformsType value) {
        this.applicablePlatforms = value;
    }

    /**
     * Gets the value of the backgroundDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BackgroundDetailsType }
     *     
     */
    public BackgroundDetailsType getBackgroundDetails() {
        return backgroundDetails;
    }

    /**
     * Sets the value of the backgroundDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackgroundDetailsType }
     *     
     */
    public void setBackgroundDetails(BackgroundDetailsType value) {
        this.backgroundDetails = value;
    }

    /**
     * Gets the value of the alternateTerms property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateTermsType }
     *     
     */
    public AlternateTermsType getAlternateTerms() {
        return alternateTerms;
    }

    /**
     * Sets the value of the alternateTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateTermsType }
     *     
     */
    public void setAlternateTerms(AlternateTermsType value) {
        this.alternateTerms = value;
    }

    /**
     * Gets the value of the modesOfIntroduction property.
     * 
     * @return
     *     possible object is
     *     {@link ModesOfIntroductionType }
     *     
     */
    public ModesOfIntroductionType getModesOfIntroduction() {
        return modesOfIntroduction;
    }

    /**
     * Sets the value of the modesOfIntroduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModesOfIntroductionType }
     *     
     */
    public void setModesOfIntroduction(ModesOfIntroductionType value) {
        this.modesOfIntroduction = value;
    }

    /**
     * Gets the value of the exploitationFactors property.
     * 
     * @return
     *     possible object is
     *     {@link ExploitationFactorsType }
     *     
     */
    public ExploitationFactorsType getExploitationFactors() {
        return exploitationFactors;
    }

    /**
     * Sets the value of the exploitationFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExploitationFactorsType }
     *     
     */
    public void setExploitationFactors(ExploitationFactorsType value) {
        this.exploitationFactors = value;
    }

    /**
     * Gets the value of the likelihoodOfExploit property.
     * 
     * @return
     *     possible object is
     *     {@link LikelihoodEnumeration }
     *     
     */
    public LikelihoodEnumeration getLikelihoodOfExploit() {
        return likelihoodOfExploit;
    }

    /**
     * Sets the value of the likelihoodOfExploit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LikelihoodEnumeration }
     *     
     */
    public void setLikelihoodOfExploit(LikelihoodEnumeration value) {
        this.likelihoodOfExploit = value;
    }

    /**
     * Gets the value of the commonConsequences property.
     * 
     * @return
     *     possible object is
     *     {@link CommonConsequencesType }
     *     
     */
    public CommonConsequencesType getCommonConsequences() {
        return commonConsequences;
    }

    /**
     * Sets the value of the commonConsequences property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonConsequencesType }
     *     
     */
    public void setCommonConsequences(CommonConsequencesType value) {
        this.commonConsequences = value;
    }

    /**
     * Gets the value of the detectionMethods property.
     * 
     * @return
     *     possible object is
     *     {@link DetectionMethodsType }
     *     
     */
    public DetectionMethodsType getDetectionMethods() {
        return detectionMethods;
    }

    /**
     * Sets the value of the detectionMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetectionMethodsType }
     *     
     */
    public void setDetectionMethods(DetectionMethodsType value) {
        this.detectionMethods = value;
    }

    /**
     * Gets the value of the potentialMitigations property.
     * 
     * @return
     *     possible object is
     *     {@link PotentialMitigationsType }
     *     
     */
    public PotentialMitigationsType getPotentialMitigations() {
        return potentialMitigations;
    }

    /**
     * Sets the value of the potentialMitigations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PotentialMitigationsType }
     *     
     */
    public void setPotentialMitigations(PotentialMitigationsType value) {
        this.potentialMitigations = value;
    }

    /**
     * Gets the value of the demonstrativeExamples property.
     * 
     * @return
     *     possible object is
     *     {@link DemonstrativeExamplesType }
     *     
     */
    public DemonstrativeExamplesType getDemonstrativeExamples() {
        return demonstrativeExamples;
    }

    /**
     * Sets the value of the demonstrativeExamples property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemonstrativeExamplesType }
     *     
     */
    public void setDemonstrativeExamples(DemonstrativeExamplesType value) {
        this.demonstrativeExamples = value;
    }

    /**
     * Gets the value of the observedExamples property.
     * 
     * @return
     *     possible object is
     *     {@link ObservedExampleType }
     *     
     */
    public ObservedExampleType getObservedExamples() {
        return observedExamples;
    }

    /**
     * Sets the value of the observedExamples property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservedExampleType }
     *     
     */
    public void setObservedExamples(ObservedExampleType value) {
        this.observedExamples = value;
    }

    /**
     * Gets the value of the functionalAreas property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionalAreasType }
     *     
     */
    public FunctionalAreasType getFunctionalAreas() {
        return functionalAreas;
    }

    /**
     * Sets the value of the functionalAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionalAreasType }
     *     
     */
    public void setFunctionalAreas(FunctionalAreasType value) {
        this.functionalAreas = value;
    }

    /**
     * Gets the value of the affectedResources property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedResourcesType }
     *     
     */
    public AffectedResourcesType getAffectedResources() {
        return affectedResources;
    }

    /**
     * Sets the value of the affectedResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedResourcesType }
     *     
     */
    public void setAffectedResources(AffectedResourcesType value) {
        this.affectedResources = value;
    }

    /**
     * Gets the value of the taxonomyMappings property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonomyMappingsType }
     *     
     */
    public TaxonomyMappingsType getTaxonomyMappings() {
        return taxonomyMappings;
    }

    /**
     * Sets the value of the taxonomyMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonomyMappingsType }
     *     
     */
    public void setTaxonomyMappings(TaxonomyMappingsType value) {
        this.taxonomyMappings = value;
    }

    /**
     * Gets the value of the relatedAttackPatterns property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedAttackPatternsType }
     *     
     */
    public RelatedAttackPatternsType getRelatedAttackPatterns() {
        return relatedAttackPatterns;
    }

    /**
     * Sets the value of the relatedAttackPatterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedAttackPatternsType }
     *     
     */
    public void setRelatedAttackPatterns(RelatedAttackPatternsType value) {
        this.relatedAttackPatterns = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *     
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *     
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link NotesType }
     *     
     */
    public NotesType getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotesType }
     *     
     */
    public void setNotes(NotesType value) {
        this.notes = value;
    }

    /**
     * Gets the value of the contentHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ContentHistoryType }
     *     
     */
    public ContentHistoryType getContentHistory() {
        return contentHistory;
    }

    /**
     * Sets the value of the contentHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentHistoryType }
     *     
     */
    public void setContentHistory(ContentHistoryType value) {
        this.contentHistory = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the abstraction property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractionEnumeration }
     *     
     */
    public AbstractionEnumeration getAbstraction() {
        return abstraction;
    }

    /**
     * Sets the value of the abstraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractionEnumeration }
     *     
     */
    public void setAbstraction(AbstractionEnumeration value) {
        this.abstraction = value;
    }

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link StructureEnumeration }
     *     
     */
    public StructureEnumeration getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureEnumeration }
     *     
     */
    public void setStructure(StructureEnumeration value) {
        this.structure = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusEnumeration }
     *     
     */
    public StatusEnumeration getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusEnumeration }
     *     
     */
    public void setStatus(StatusEnumeration value) {
        this.status = value;
    }

}
