//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractionEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AbstractionEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Pillar"/>
 *     &lt;enumeration value="Class"/>
 *     &lt;enumeration value="Base"/>
 *     &lt;enumeration value="Variant"/>
 *     &lt;enumeration value="Compound"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AbstractionEnumeration")
@XmlEnum
public enum AbstractionEnumeration {

    @XmlEnumValue("Pillar")
    PILLAR("Pillar"),
    @XmlEnumValue("Class")
    CLASS("Class"),
    @XmlEnumValue("Base")
    BASE("Base"),
    @XmlEnumValue("Variant")
    VARIANT("Variant"),
    @XmlEnumValue("Compound")
    COMPOUND("Compound");
    private final String value;

    AbstractionEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AbstractionEnumeration fromValue(String v) {
        for (AbstractionEnumeration c: AbstractionEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
