//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArchitectureNameEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ArchitectureNameEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Alpha"/>
 *     &lt;enumeration value="ARM"/>
 *     &lt;enumeration value="Itanium"/>
 *     &lt;enumeration value="Power Architecture"/>
 *     &lt;enumeration value="SPARC"/>
 *     &lt;enumeration value="x86"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ArchitectureNameEnumeration")
@XmlEnum
public enum ArchitectureNameEnumeration {

    @XmlEnumValue("Alpha")
    ALPHA("Alpha"),
    ARM("ARM"),
    @XmlEnumValue("Itanium")
    ITANIUM("Itanium"),
    @XmlEnumValue("Power Architecture")
    POWER_ARCHITECTURE("Power Architecture"),
    SPARC("SPARC"),
    @XmlEnumValue("x86")
    X_86("x86"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ArchitectureNameEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ArchitectureNameEnumeration fromValue(String v) {
        for (ArchitectureNameEnumeration c: ArchitectureNameEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
