//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * The optional Demonstrative_Example_ID attribute is used by the internal CWE team to uniquely identify examples that are repeated across any number of individual weaknesses. To help make sure that the details of these common examples stay synchronized, the Demonstrative_Example_ID is used to quickly identify those examples across CWE that should be identical. The identifier is a string and should match the following format: DX-1.
 * 
 * <p>Java class for DemonstrativeExamplesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DemonstrativeExamplesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Demonstrative_Example" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Title_Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Intro_Text" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="Body_Text" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
 *                     &lt;element name="Example_Code" type="{http://cwe.mitre.org/cwe-6}StructuredCodeType"/>
 *                   &lt;/choice>
 *                   &lt;element name="References" type="{http://cwe.mitre.org/cwe-6}ReferencesType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Demonstrative_Example_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DemonstrativeExamplesType", propOrder = {
    "demonstrativeExample"
})
public class DemonstrativeExamplesType {

    @XmlElement(name = "Demonstrative_Example", required = true)
    protected List<DemonstrativeExamplesType.DemonstrativeExample> demonstrativeExample;

    /**
     * Gets the value of the demonstrativeExample property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the demonstrativeExample property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDemonstrativeExample().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DemonstrativeExamplesType.DemonstrativeExample }
     * 
     * 
     */
    public List<DemonstrativeExamplesType.DemonstrativeExample> getDemonstrativeExample() {
        if (demonstrativeExample == null) {
            demonstrativeExample = new ArrayList<DemonstrativeExamplesType.DemonstrativeExample>();
        }
        return this.demonstrativeExample;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Title_Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Intro_Text" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="Body_Text" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
     *           &lt;element name="Example_Code" type="{http://cwe.mitre.org/cwe-6}StructuredCodeType"/>
     *         &lt;/choice>
     *         &lt;element name="References" type="{http://cwe.mitre.org/cwe-6}ReferencesType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Demonstrative_Example_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titleText",
        "introText",
        "bodyTextOrExampleCode",
        "references"
    })
    public static class DemonstrativeExample {

        @XmlElement(name = "Title_Text")
        protected String titleText;
        @XmlElement(name = "Intro_Text", required = true)
        protected StructuredTextType introText;
        @XmlElements({
            @XmlElement(name = "Body_Text", type = StructuredTextType.class),
            @XmlElement(name = "Example_Code", type = StructuredCodeType.class)
        })
        protected List<Object> bodyTextOrExampleCode;
        @XmlElement(name = "References")
        protected ReferencesType references;
        @XmlAttribute(name = "Demonstrative_Example_ID")
        protected String demonstrativeExampleID;

        /**
         * Gets the value of the titleText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitleText() {
            return titleText;
        }

        /**
         * Sets the value of the titleText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitleText(String value) {
            this.titleText = value;
        }

        /**
         * Gets the value of the introText property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredTextType }
         *     
         */
        public StructuredTextType getIntroText() {
            return introText;
        }

        /**
         * Sets the value of the introText property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredTextType }
         *     
         */
        public void setIntroText(StructuredTextType value) {
            this.introText = value;
        }

        /**
         * Gets the value of the bodyTextOrExampleCode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bodyTextOrExampleCode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBodyTextOrExampleCode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StructuredTextType }
         * {@link StructuredCodeType }
         * 
         * 
         */
        public List<Object> getBodyTextOrExampleCode() {
            if (bodyTextOrExampleCode == null) {
                bodyTextOrExampleCode = new ArrayList<Object>();
            }
            return this.bodyTextOrExampleCode;
        }

        /**
         * Gets the value of the references property.
         * 
         * @return
         *     possible object is
         *     {@link ReferencesType }
         *     
         */
        public ReferencesType getReferences() {
            return references;
        }

        /**
         * Sets the value of the references property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferencesType }
         *     
         */
        public void setReferences(ReferencesType value) {
            this.references = value;
        }

        /**
         * Gets the value of the demonstrativeExampleID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDemonstrativeExampleID() {
            return demonstrativeExampleID;
        }

        /**
         * Sets the value of the demonstrativeExampleID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDemonstrativeExampleID(String value) {
            this.demonstrativeExampleID = value;
        }

    }

}
