//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MitigationStrategyEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MitigationStrategyEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Attack Surface Reduction"/>
 *     &lt;enumeration value="Compilation or Build Hardening"/>
 *     &lt;enumeration value="Enforcement by Conversion"/>
 *     &lt;enumeration value="Environment Hardening"/>
 *     &lt;enumeration value="Firewall"/>
 *     &lt;enumeration value="Input Validation"/>
 *     &lt;enumeration value="Language Selection"/>
 *     &lt;enumeration value="Libraries or Frameworks"/>
 *     &lt;enumeration value="Resource Limitation"/>
 *     &lt;enumeration value="Output Encoding"/>
 *     &lt;enumeration value="Parameterization"/>
 *     &lt;enumeration value="Refactoring"/>
 *     &lt;enumeration value="Sandbox or Jail"/>
 *     &lt;enumeration value="Separation of Privilege"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MitigationStrategyEnumeration")
@XmlEnum
public enum MitigationStrategyEnumeration {

    @XmlEnumValue("Attack Surface Reduction")
    ATTACK_SURFACE_REDUCTION("Attack Surface Reduction"),
    @XmlEnumValue("Compilation or Build Hardening")
    COMPILATION_OR_BUILD_HARDENING("Compilation or Build Hardening"),
    @XmlEnumValue("Enforcement by Conversion")
    ENFORCEMENT_BY_CONVERSION("Enforcement by Conversion"),
    @XmlEnumValue("Environment Hardening")
    ENVIRONMENT_HARDENING("Environment Hardening"),
    @XmlEnumValue("Firewall")
    FIREWALL("Firewall"),
    @XmlEnumValue("Input Validation")
    INPUT_VALIDATION("Input Validation"),
    @XmlEnumValue("Language Selection")
    LANGUAGE_SELECTION("Language Selection"),
    @XmlEnumValue("Libraries or Frameworks")
    LIBRARIES_OR_FRAMEWORKS("Libraries or Frameworks"),
    @XmlEnumValue("Resource Limitation")
    RESOURCE_LIMITATION("Resource Limitation"),
    @XmlEnumValue("Output Encoding")
    OUTPUT_ENCODING("Output Encoding"),
    @XmlEnumValue("Parameterization")
    PARAMETERIZATION("Parameterization"),
    @XmlEnumValue("Refactoring")
    REFACTORING("Refactoring"),
    @XmlEnumValue("Sandbox or Jail")
    SANDBOX_OR_JAIL("Sandbox or Jail"),
    @XmlEnumValue("Separation of Privilege")
    SEPARATION_OF_PRIVILEGE("Separation of Privilege");
    private final String value;

    MitigationStrategyEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MitigationStrategyEnumeration fromValue(String v) {
        for (MitigationStrategyEnumeration c: MitigationStrategyEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
