//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The optional Mitigation_ID attribute is used by the internal CWE team to uniquely identify mitigations that are repeated across any number of individual weaknesses. To help make sure that the details of these common mitigations stay synchronized, the Mitigation_ID is used to quickly identify those mitigation elements across CWE that should be identical. The identifier is a string and should match the following format: MIT-1.
 * 
 * <p>Java class for PotentialMitigationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PotentialMitigationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Mitigation" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Phase" type="{http://cwe.mitre.org/cwe-6}PhaseEnumeration" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Strategy" type="{http://cwe.mitre.org/cwe-6}MitigationStrategyEnumeration" minOccurs="0"/>
 *                   &lt;element name="Description" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
 *                   &lt;element name="Effectiveness" type="{http://cwe.mitre.org/cwe-6}EffectivenessEnumeration" minOccurs="0"/>
 *                   &lt;element name="Effectiveness_Notes" type="{http://cwe.mitre.org/cwe-6}StructuredTextType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Mitigation_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PotentialMitigationsType", propOrder = {
    "mitigation"
})
public class PotentialMitigationsType {

    @XmlElement(name = "Mitigation", required = true)
    protected List<PotentialMitigationsType.Mitigation> mitigation;

    /**
     * Gets the value of the mitigation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mitigation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMitigation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PotentialMitigationsType.Mitigation }
     * 
     * 
     */
    public List<PotentialMitigationsType.Mitigation> getMitigation() {
        if (mitigation == null) {
            mitigation = new ArrayList<PotentialMitigationsType.Mitigation>();
        }
        return this.mitigation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Phase" type="{http://cwe.mitre.org/cwe-6}PhaseEnumeration" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Strategy" type="{http://cwe.mitre.org/cwe-6}MitigationStrategyEnumeration" minOccurs="0"/>
     *         &lt;element name="Description" type="{http://cwe.mitre.org/cwe-6}StructuredTextType"/>
     *         &lt;element name="Effectiveness" type="{http://cwe.mitre.org/cwe-6}EffectivenessEnumeration" minOccurs="0"/>
     *         &lt;element name="Effectiveness_Notes" type="{http://cwe.mitre.org/cwe-6}StructuredTextType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Mitigation_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phase",
        "strategy",
        "description",
        "effectiveness",
        "effectivenessNotes"
    })
    public static class Mitigation {

        @XmlElement(name = "Phase")
        @XmlSchemaType(name = "string")
        protected List<PhaseEnumeration> phase;
        @XmlElement(name = "Strategy")
        @XmlSchemaType(name = "string")
        protected MitigationStrategyEnumeration strategy;
        @XmlElement(name = "Description", required = true)
        protected StructuredTextType description;
        @XmlElement(name = "Effectiveness")
        @XmlSchemaType(name = "string")
        protected EffectivenessEnumeration effectiveness;
        @XmlElement(name = "Effectiveness_Notes")
        protected StructuredTextType effectivenessNotes;
        @XmlAttribute(name = "Mitigation_ID")
        protected String mitigationID;

        /**
         * Gets the value of the phase property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the phase property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhase().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PhaseEnumeration }
         * 
         * 
         */
        public List<PhaseEnumeration> getPhase() {
            if (phase == null) {
                phase = new ArrayList<PhaseEnumeration>();
            }
            return this.phase;
        }

        /**
         * Gets the value of the strategy property.
         * 
         * @return
         *     possible object is
         *     {@link MitigationStrategyEnumeration }
         *     
         */
        public MitigationStrategyEnumeration getStrategy() {
            return strategy;
        }

        /**
         * Sets the value of the strategy property.
         * 
         * @param value
         *     allowed object is
         *     {@link MitigationStrategyEnumeration }
         *     
         */
        public void setStrategy(MitigationStrategyEnumeration value) {
            this.strategy = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredTextType }
         *     
         */
        public StructuredTextType getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredTextType }
         *     
         */
        public void setDescription(StructuredTextType value) {
            this.description = value;
        }

        /**
         * Gets the value of the effectiveness property.
         * 
         * @return
         *     possible object is
         *     {@link EffectivenessEnumeration }
         *     
         */
        public EffectivenessEnumeration getEffectiveness() {
            return effectiveness;
        }

        /**
         * Sets the value of the effectiveness property.
         * 
         * @param value
         *     allowed object is
         *     {@link EffectivenessEnumeration }
         *     
         */
        public void setEffectiveness(EffectivenessEnumeration value) {
            this.effectiveness = value;
        }

        /**
         * Gets the value of the effectivenessNotes property.
         * 
         * @return
         *     possible object is
         *     {@link StructuredTextType }
         *     
         */
        public StructuredTextType getEffectivenessNotes() {
            return effectivenessNotes;
        }

        /**
         * Sets the value of the effectivenessNotes property.
         * 
         * @param value
         *     allowed object is
         *     {@link StructuredTextType }
         *     
         */
        public void setEffectivenessNotes(StructuredTextType value) {
            this.effectivenessNotes = value;
        }

        /**
         * Gets the value of the mitigationID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMitigationID() {
            return mitigationID;
        }

        /**
         * Sets the value of the mitigationID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMitigationID(String value) {
            this.mitigationID = value;
        }

    }

}
