//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TechnicalImpactEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TechnicalImpactEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Modify Memory"/>
 *     &lt;enumeration value="Read Memory"/>
 *     &lt;enumeration value="Modify Files or Directories"/>
 *     &lt;enumeration value="Read Files or Directories"/>
 *     &lt;enumeration value="Modify Application Data"/>
 *     &lt;enumeration value="Read Application Data"/>
 *     &lt;enumeration value="DoS: Crash, Exit, or Restart"/>
 *     &lt;enumeration value="DoS: Amplification"/>
 *     &lt;enumeration value="DoS: Instability"/>
 *     &lt;enumeration value="DoS: Resource Consumption (CPU)"/>
 *     &lt;enumeration value="DoS: Resource Consumption (Memory)"/>
 *     &lt;enumeration value="DoS: Resource Consumption (Other)"/>
 *     &lt;enumeration value="Execute Unauthorized Code or Commands"/>
 *     &lt;enumeration value="Gain Privileges or Assume Identity"/>
 *     &lt;enumeration value="Bypass Protection Mechanism"/>
 *     &lt;enumeration value="Hide Activities"/>
 *     &lt;enumeration value="Alter Execution Logic"/>
 *     &lt;enumeration value="Quality Degradation"/>
 *     &lt;enumeration value="Unexpected State"/>
 *     &lt;enumeration value="Varies by Context"/>
 *     &lt;enumeration value="Reduce Maintainability"/>
 *     &lt;enumeration value="Reduce Performance"/>
 *     &lt;enumeration value="Reduce Reliability"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TechnicalImpactEnumeration")
@XmlEnum
public enum TechnicalImpactEnumeration {

    @XmlEnumValue("Modify Memory")
    MODIFY_MEMORY("Modify Memory"),
    @XmlEnumValue("Read Memory")
    READ_MEMORY("Read Memory"),
    @XmlEnumValue("Modify Files or Directories")
    MODIFY_FILES_OR_DIRECTORIES("Modify Files or Directories"),
    @XmlEnumValue("Read Files or Directories")
    READ_FILES_OR_DIRECTORIES("Read Files or Directories"),
    @XmlEnumValue("Modify Application Data")
    MODIFY_APPLICATION_DATA("Modify Application Data"),
    @XmlEnumValue("Read Application Data")
    READ_APPLICATION_DATA("Read Application Data"),
    @XmlEnumValue("DoS: Crash, Exit, or Restart")
    DO_S_CRASH_EXIT_OR_RESTART("DoS: Crash, Exit, or Restart"),
    @XmlEnumValue("DoS: Amplification")
    DO_S_AMPLIFICATION("DoS: Amplification"),
    @XmlEnumValue("DoS: Instability")
    DO_S_INSTABILITY("DoS: Instability"),
    @XmlEnumValue("DoS: Resource Consumption (CPU)")
    DO_S_RESOURCE_CONSUMPTION_CPU("DoS: Resource Consumption (CPU)"),
    @XmlEnumValue("DoS: Resource Consumption (Memory)")
    DO_S_RESOURCE_CONSUMPTION_MEMORY("DoS: Resource Consumption (Memory)"),
    @XmlEnumValue("DoS: Resource Consumption (Other)")
    DO_S_RESOURCE_CONSUMPTION_OTHER("DoS: Resource Consumption (Other)"),
    @XmlEnumValue("Execute Unauthorized Code or Commands")
    EXECUTE_UNAUTHORIZED_CODE_OR_COMMANDS("Execute Unauthorized Code or Commands"),
    @XmlEnumValue("Gain Privileges or Assume Identity")
    GAIN_PRIVILEGES_OR_ASSUME_IDENTITY("Gain Privileges or Assume Identity"),
    @XmlEnumValue("Bypass Protection Mechanism")
    BYPASS_PROTECTION_MECHANISM("Bypass Protection Mechanism"),
    @XmlEnumValue("Hide Activities")
    HIDE_ACTIVITIES("Hide Activities"),
    @XmlEnumValue("Alter Execution Logic")
    ALTER_EXECUTION_LOGIC("Alter Execution Logic"),
    @XmlEnumValue("Quality Degradation")
    QUALITY_DEGRADATION("Quality Degradation"),
    @XmlEnumValue("Unexpected State")
    UNEXPECTED_STATE("Unexpected State"),
    @XmlEnumValue("Varies by Context")
    VARIES_BY_CONTEXT("Varies by Context"),
    @XmlEnumValue("Reduce Maintainability")
    REDUCE_MAINTAINABILITY("Reduce Maintainability"),
    @XmlEnumValue("Reduce Performance")
    REDUCE_PERFORMANCE("Reduce Performance"),
    @XmlEnumValue("Reduce Reliability")
    REDUCE_RELIABILITY("Reduce Reliability"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    TechnicalImpactEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TechnicalImpactEnumeration fromValue(String v) {
        for (TechnicalImpactEnumeration c: TechnicalImpactEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
