//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.nvd.jaxb.cwe;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TechnologyNameEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TechnologyNameEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Web Server"/>
 *     &lt;enumeration value="Database Server"/>
 *     &lt;enumeration value="Accelerator IP"/>
 *     &lt;enumeration value="Analog and Mixed Signal IP"/>
 *     &lt;enumeration value="Audio/Video IP"/>
 *     &lt;enumeration value="Bus/Interface IP"/>
 *     &lt;enumeration value="Clock/Counter IP"/>
 *     &lt;enumeration value="Communication IP"/>
 *     &lt;enumeration value="Controller IP"/>
 *     &lt;enumeration value="Memory IP"/>
 *     &lt;enumeration value="Microcontroller IP"/>
 *     &lt;enumeration value="Network on Chip IP"/>
 *     &lt;enumeration value="Power Management IP"/>
 *     &lt;enumeration value="Processor IP"/>
 *     &lt;enumeration value="Security IP"/>
 *     &lt;enumeration value="Sensor IP"/>
 *     &lt;enumeration value="Storage IP"/>
 *     &lt;enumeration value="Test/Debug IP"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TechnologyNameEnumeration")
@XmlEnum
public enum TechnologyNameEnumeration {

    @XmlEnumValue("Web Server")
    WEB_SERVER("Web Server"),
    @XmlEnumValue("Database Server")
    DATABASE_SERVER("Database Server"),

    /**
     * IP dedicated to offload a specific workload to enhance performance: DSP, packet processing, mathematical, compression, etc.
     * 
     */
    @XmlEnumValue("Accelerator IP")
    ACCELERATOR_IP("Accelerator IP"),

    /**
     * IP that controls/senses the electricals for communication which receives/transmits signals conditioned outside of a systems digital domain.
     * 
     */
    @XmlEnumValue("Analog and Mixed Signal IP")
    ANALOG_AND_MIXED_SIGNAL_IP("Analog and Mixed Signal IP"),

    /**
     * IP designed to manipulate audio/video data: coders/decoders, speech recognition, format converters, etc.
     * 
     */
    @XmlEnumValue("Audio/Video IP")
    AUDIO_VIDEO_IP("Audio/Video IP"),

    /**
     * IP implementing an interconnect among elements in a computing system: I2C, PCIe, DDR, MMC, USB, GPIO, NoC, etc.
     * 
     */
    @XmlEnumValue("Bus/Interface IP")
    BUS_INTERFACE_IP("Bus/Interface IP"),

    /**
     * IP reflecting the passage of time in oscillations or human units: Real Time Clock, Watchdog, Monotonic Counter, etc.
     * 
     */
    @XmlEnumValue("Clock/Counter IP")
    CLOCK_COUNTER_IP("Clock/Counter IP"),

    /**
     * IP designed to transmit/receive information: Modulator/Demodulator, GPS, 802.11, Bluetooth, CDMA/DSM, etc.
     * 
     */
    @XmlEnumValue("Communication IP")
    COMMUNICATION_IP("Communication IP"),

    /**
     * IP circuit hard-wired (e.g., an FSM) to react in a closed-loop control system or other limited context, to control another entity: Arbiter, APIC, USB, Peripheral, Memory, Storage, etc.
     * 
     */
    @XmlEnumValue("Controller IP")
    CONTROLLER_IP("Controller IP"),

    /**
     * IP implementing volatile (transient) data storage: DRAM, SRAM, etc.
     * 
     */
    @XmlEnumValue("Memory IP")
    MEMORY_IP("Memory IP"),

    /**
     * IP implementing a specialized processor acting as a programmable controller.
     * 
     */
    @XmlEnumValue("Microcontroller IP")
    MICROCONTROLLER_IP("Microcontroller IP"),
    @XmlEnumValue("Network on Chip IP")
    NETWORK_ON_CHIP_IP("Network on Chip IP"),

    /**
     * IP that controls and/or monitors the power state of a system: voltage regulators, power controllers, power monitors, etc.
     * 
     */
    @XmlEnumValue("Power Management IP")
    POWER_MANAGEMENT_IP("Power Management IP"),

    /**
     * IP implementing a general-purpose computing engine: CPU, GPU, RISC, CISC, etc.
     * 
     */
    @XmlEnumValue("Processor IP")
    PROCESSOR_IP("Processor IP"),

    /**
     * IP designed to protect assets: cryptography, auth, tamper detection, etc.
     * 
     */
    @XmlEnumValue("Security IP")
    SECURITY_IP("Security IP"),
    @XmlEnumValue("Sensor IP")
    SENSOR_IP("Sensor IP"),
    @XmlEnumValue("Storage IP")
    STORAGE_IP("Storage IP"),

    /**
     * IP designed to verify functionality and identify root cause of defects: JTAG, BIST, boundary scan, pattern generator, etc.
     * 
     */
    @XmlEnumValue("Test/Debug IP")
    TEST_DEBUG_IP("Test/Debug IP"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    TechnologyNameEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TechnologyNameEnumeration fromValue(String v) {
        for (TechnologyNameEnumeration c: TechnologyNameEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
