//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.cwe.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LanguageClassEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LanguageClassEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Assembly"/>
 *     &lt;enumeration value="Compiled"/>
 *     &lt;enumeration value="Interpreted"/>
 *     &lt;enumeration value="Language-Independent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LanguageClassEnumeration")
@XmlEnum
public enum LanguageClassEnumeration {

    @XmlEnumValue("Assembly")
    ASSEMBLY("Assembly"),
    @XmlEnumValue("Compiled")
    COMPILED("Compiled"),
    @XmlEnumValue("Interpreted")
    INTERPRETED("Interpreted"),
    @XmlEnumValue("Language-Independent")
    LANGUAGE_INDEPENDENT("Language-Independent");
    private final String value;

    LanguageClassEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageClassEnumeration fromValue(String v) {
        for (LanguageClassEnumeration c: LanguageClassEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
