//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.cwe.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrevalenceEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrevalenceEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Often"/>
 *     &lt;enumeration value="Sometimes"/>
 *     &lt;enumeration value="Rarely"/>
 *     &lt;enumeration value="Undetermined"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrevalenceEnumeration")
@XmlEnum
public enum PrevalenceEnumeration {

    @XmlEnumValue("Often")
    OFTEN("Often"),
    @XmlEnumValue("Sometimes")
    SOMETIMES("Sometimes"),
    @XmlEnumValue("Rarely")
    RARELY("Rarely"),
    @XmlEnumValue("Undetermined")
    UNDETERMINED("Undetermined");
    private final String value;

    PrevalenceEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrevalenceEnumeration fromValue(String v) {
        for (PrevalenceEnumeration c: PrevalenceEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
