//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.cwe.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * The RelationshipsType complex type provides elements to show the associated relationships with a given view or category. The Member_Of element is used to denote the individual categories that are included as part of the target view. The Has_Member element is used to define the weaknesses or other categories that are grouped together by a category. In both cases, the required MemberType's CWE_ID attribute specifies the unique CWE ID that is the target entry of the relationship, while the View_ID specifies which view the given relationship is relevant to.
 * 
 * <p>Java class for RelationshipsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationshipsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Member_Of" type="{http://cwe.mitre.org/cwe-6}MemberType" maxOccurs="unbounded"/>
 *           &lt;element name="Has_Member" type="{http://cwe.mitre.org/cwe-6}MemberType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="Has_Member" type="{http://cwe.mitre.org/cwe-6}MemberType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationshipsType", propOrder = {
    "content"
})
public class RelationshipsType {

    @XmlElementRefs({
        @XmlElementRef(name = "Member_Of", namespace = "http://cwe.mitre.org/cwe-6", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Has_Member", namespace = "http://cwe.mitre.org/cwe-6", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<MemberType>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "HasMember" is used by two different parts of a schema. See: 
     * line 523 of file:/D:/Workspace/beam-example/word-count-beam/target/cwe_schema_latest_mitre.xsd
     * line 521 of file:/D:/Workspace/beam-example/word-count-beam/target/cwe_schema_latest_mitre.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link MemberType }{@code >}
     * {@link JAXBElement }{@code <}{@link MemberType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<MemberType>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<MemberType>>();
        }
        return this.content;
    }

}
