//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.cwe.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedNatureEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelatedNatureEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ChildOf"/>
 *     &lt;enumeration value="ParentOf"/>
 *     &lt;enumeration value="StartsWith"/>
 *     &lt;enumeration value="CanFollow"/>
 *     &lt;enumeration value="CanPrecede"/>
 *     &lt;enumeration value="RequiredBy"/>
 *     &lt;enumeration value="Requires"/>
 *     &lt;enumeration value="CanAlsoBe"/>
 *     &lt;enumeration value="PeerOf"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RelatedNatureEnumeration")
@XmlEnum
public enum RelatedNatureEnumeration {

    @XmlEnumValue("ChildOf")
    CHILD_OF("ChildOf"),
    @XmlEnumValue("ParentOf")
    PARENT_OF("ParentOf"),
    @XmlEnumValue("StartsWith")
    STARTS_WITH("StartsWith"),
    @XmlEnumValue("CanFollow")
    CAN_FOLLOW("CanFollow"),
    @XmlEnumValue("CanPrecede")
    CAN_PRECEDE("CanPrecede"),
    @XmlEnumValue("RequiredBy")
    REQUIRED_BY("RequiredBy"),
    @XmlEnumValue("Requires")
    REQUIRES("Requires"),
    @XmlEnumValue("CanAlsoBe")
    CAN_ALSO_BE("CanAlsoBe"),
    @XmlEnumValue("PeerOf")
    PEER_OF("PeerOf");
    private final String value;

    RelatedNatureEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RelatedNatureEnumeration fromValue(String v) {
        for (RelatedNatureEnumeration c: RelatedNatureEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
