//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 11:40:26 PM IST 
//


package com.csw.data.mitre.cwe.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StakeholderEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StakeholderEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Academic Researchers"/>
 *     &lt;enumeration value="Applied Researchers"/>
 *     &lt;enumeration value="Assessment Teams"/>
 *     &lt;enumeration value="Assessment Tool Vendors"/>
 *     &lt;enumeration value="CWE Team"/>
 *     &lt;enumeration value="Educators"/>
 *     &lt;enumeration value="Hardware Designers"/>
 *     &lt;enumeration value="Information Providers"/>
 *     &lt;enumeration value="Product Customers"/>
 *     &lt;enumeration value="Product Vendors"/>
 *     &lt;enumeration value="Software Developers"/>
 *     &lt;enumeration value="Vulnerability Analysts"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StakeholderEnumeration")
@XmlEnum
public enum StakeholderEnumeration {

    @XmlEnumValue("Academic Researchers")
    ACADEMIC_RESEARCHERS("Academic Researchers"),
    @XmlEnumValue("Applied Researchers")
    APPLIED_RESEARCHERS("Applied Researchers"),
    @XmlEnumValue("Assessment Teams")
    ASSESSMENT_TEAMS("Assessment Teams"),
    @XmlEnumValue("Assessment Tool Vendors")
    ASSESSMENT_TOOL_VENDORS("Assessment Tool Vendors"),
    @XmlEnumValue("CWE Team")
    CWE_TEAM("CWE Team"),
    @XmlEnumValue("Educators")
    EDUCATORS("Educators"),
    @XmlEnumValue("Hardware Designers")
    HARDWARE_DESIGNERS("Hardware Designers"),
    @XmlEnumValue("Information Providers")
    INFORMATION_PROVIDERS("Information Providers"),
    @XmlEnumValue("Product Customers")
    PRODUCT_CUSTOMERS("Product Customers"),
    @XmlEnumValue("Product Vendors")
    PRODUCT_VENDORS("Product Vendors"),
    @XmlEnumValue("Software Developers")
    SOFTWARE_DEVELOPERS("Software Developers"),
    @XmlEnumValue("Vulnerability Analysts")
    VULNERABILITY_ANALYSTS("Vulnerability Analysts"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    StakeholderEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StakeholderEnumeration fromValue(String v) {
        for (StakeholderEnumeration c: StakeholderEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
